version: '3'

services:
  nginx-server:
    build: ./nginx-server
    container_name: nginx-server
    volumes:
      - nginx_data:/usr/share/nginx/html    #volume for nginx data
    networks:
      - my_network

  apache-server:
    build: ./apache-server
    container_name: apache-server
    volumes:
      - apache_data:/var/www/html           #volume for apache data
    networks:
      - my_network

  reverse-proxy:
    build: ./reverse-proxy
    ports:
      - "80:80"
    depends_on:
      - nginx-server
      - apache-server
    container_name: reverse-proxy
    networks:
      - my_network

volumes:
  nginx_data:
  apache_data:

networks:
  my_network:
    driver: bridge
