apiVersion: v1
kind: Service
metadata:
  name: alien-tetris-service
spec:
  selector:
    app: alien-tetris
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
